defmodule Thinktank.Perspective do
  @moduledoc """
  A research perspective: role + model + system prompt.

  Generated by the Router from a research question, or manually
  specified via `--roles`. Consumed by the Orchestrator to dispatch
  parallel agent calls.
  """

  @enforce_keys [:role, :model, :system_prompt]
  defstruct [:role, :model, :system_prompt, priority: 0]

  @type t :: %__MODULE__{
          role: String.t(),
          model: String.t(),
          system_prompt: String.t(),
          priority: non_neg_integer()
        }

  @doc """
  Build a Perspective from a decoded JSON map.

  Expects keys: "role", "model", "system_prompt", and optionally "priority".
  """
  @spec from_map(map()) :: t()
  def from_map(%{"role" => role, "model" => model, "system_prompt" => prompt} = map) do
    %__MODULE__{
      role: role,
      model: model,
      system_prompt: prompt,
      priority: Map.get(map, "priority", 0)
    }
  end
end
